
server:
  port: 8030
  shutdown: graceful
spring:
  application:
    name: store-service
  rabbitmq:
    host: rabbit-rabbitmq.default.svc.cluster.local
    port: 5672
    username: user
    password: ${RABBIT_PASS}
    virtual-host: "/"
    ssl:
      enabled: false
      verify-hostname: false
    queues:
      service-queue: otus.store.queue
      service-answer-queue: otus.delivery.queue
    exchanges:
      service-exchange: otus.store.exchange
      service-answer-exchange: otus.delivery.exchange
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 180000
      leak-detection-threshold: 0
      jdbc-url: ${DBURL}
      username: store_service
      password: "tGXivQhfBP"
    url: ${DBURL}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
management:
  endpoint:
    health:
      probes:
        enabled: true
    restart:
      enabled: true
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,shutdown,restart,refresh
      path-mapping:
        prometheus: metrics
      base-path: /
feign:
  autoconfiguration:
    jackson:
      enabled: true
  client:
    config:
      auth-service:
        connectionTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
logging:
  level:
    org:
      springframework:
        security: DEBUG
